export { default as Carrousel } from './Carrousel'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as ProductsSlider } from './ProductsSlider'
export { default as ProductItem } from './ProductItem'
export { default as Stars } from './Stars'